### ISSUE TITLE
Question - Have you implemented all the events?

### ISSUE THREAD

**Issue by siggerzz** [Shchepotin/vue-iro-color-picker#1]
Hey, quick question,

Looking at the code, it looks like you haven't implemented a number of events - https://iro.js.org/colorPicker_api.html#events

Is it possible to implement the `input:end` event?

`change` isn't favorable in my scenario, as I'll be calling an API.

Alternatively, let me know where to get started, and I'll try and implement this myself.

Cheers

**Comment by Shchepotin** [comment]
Hi @siggerzz I added events, please update `vue-iro-color-picker` to version `2.0.0`.

**Comment by siggerzz** [comment]
Thanks a lot!

**Comment by Shchepotin** [comment]
@siggerzz you're welcome. 🙂

**Comment by siggerzz** [comment]
Just a quick question, how do I use v-on with these events?

For example, usually I do something like `v-on:myEvent="myMethod"`

However with the event names you've chosen I don't think this works.

For example `v-on:input:end="myMethod"`

in this scenario, the value myMethod is read as a string, because of of the `:` between `input` and `end`

Let me know if i'm doing this wrong! If not, you may want to change you event names, although this will be a breaking change..

**Comment by adrianocr** [comment]
Sorry, how do I use the events? 

Would I do v-on:color:change="" or what? How does writing out the v-on: correspond to color:init, input:start, etc?

Edit: yup, that's exactly it. And then the event is accessibly via $event. Provide a callback to the v-on directive and pass $event to that callback.
