### ISSUE TITLE
re: transferring ownership

### ISSUE THREAD

**Issue by jaames** [Shchepotin/vue-iro-color-picker#2]
Hi, I'm the author of iro.js

Firstly, great work on this project! It's really cool to see that someone has made a such a nice Vue wrapper for iro.js and that they've taken the time to keep it up to date :) 

I'm currently looking into making officially supported Vue and React components for the next major version of iro.js ([5.0 discussion thread](https://github.com/jaames/iro.js/issues/83)). But since having competing Vue components for iro.js might be confusing, I was wondering if you would be open to either transferring ownership of this repo (and npm package) or perhaps giving me push access?

Of course you're absolutely welcome to help maintain this project if you'd like, and I'll make sure that you're credited for your work :)

Thanks!

**Comment by Shchepotin** [comment]
Hi! Yes, I can transfer this repo to your Github and provide access to NPM. :)

Let's move to email: vl.shchepotin@gmail.com

**Comment by jaames** [comment]
Great! Just sent you an email from mail@jamesdaniel.dev :)

Sorry for the slow response
